### ISSUE TITLE
Duplication of effort

### ISSUE THREAD

**Issue by ephja** [rafaelvasco/nimrod-glfw#10]
Do you know about my GLFW library (https://github.com/ephja/nim-glfw)?
I made the mistake of not forking your library 4 years ago or so.

**Comment by jacmoe** [comment]
It is true that there seems to be a duplication of efforts, but I think it's OK, because Rafael  decided to create a minimal wrapper and your wrapper seems to be higher level.

I personally prefer a one to one mapping. :)

**Comment by ephja** [comment]
Ok, good to know.

**Comment by rafaelvasco** [comment]
Only now seeing this :) Yeah, by default i always prefer a one to one mapping. No such thing as duplication of effort as your lib may be more useful to some and mine to others. All is good.
